DROP TABLE IF EXISTS plots;
CREATE TABLE plots
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plot_name VARCHAR(250)   NOT NULL,
    length    NUMERIC(20, 2) NOT NULL,
    width     NUMERIC(20, 2) NOT NULL,
    soil_type VARCHAR(15)
);

DROP TABLE IF EXISTS time_slots;
CREATE TABLE time_slots
(
    id             INT            NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    start_time     TIME           NOT NULL,
    duration       NUMERIC        NOT NULL,
    water_quantity NUMERIC(20, 2) NOT NULL,
    plot_id        INT            NOT NULL,
    current_status VARCHAR(20),

    CONSTRAINT time_slots_pk PRIMARY KEY (id),
    CONSTRAINT plot_fk FOREIGN KEY (plot_id) REFERENCES plots (id)
);
